# Generated by Django 4.1.2 on 2022-11-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('celery_beat', '0002_alter_author_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='quote',
        ),
        migrations.AddField(
            model_name='quote',
            name='tags',
            field=models.ManyToManyField(to='celery_beat.tags'),
        ),
    ]
